### ISSUE TITLE
Applet not showing on Ubuntu Budgie 19.10

### ISSUE THREAD

**Issue by tleibert** [ubuntu-mate/mate-optimus#16]
The applet does not show and produces a filenotfound error:

```
mate-optimus-applet: launched.
  - nvidia-settings and prime-select detected.
  - prime-supported: Yes
mate-optimus-applet: NVIDIA Optimus supported.
Checking: intel
  - intel loaded: No
  - intel: is not supported
Checking: nvidia
  - nvidia loaded: n/a
  - prime-supported: Yes
Traceback (most recent call last):
  File "./mate-optimus-applet", line 327, in <module>
    Indicator()
  File "./mate-optimus-applet", line 188, in __init__
    self.nvidia_available = check_capability('nvidia')
  File "./mate-optimus-applet", line 121, in check_capability
    nvidia_detected(capability) and \
  File "./mate-optimus-applet", line 60, in nvidia_detected
    nvidia_detector = subprocess.Popen(['nvidia-detector'], stdout=PIPE, stderr=DEVNULL)
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'nvidia-detector': 'nvidia-detector'
```

**Comment by tleibert** [comment]
Resolved
