### ISSUE TITLE
ValueError: Namespace AppIndicator3 not available on Ubuntu 20.04

### ISSUE THREAD

**Issue by LazyHatGuy** [ubuntu-mate/mate-optimus#29]
I just installed mate-optimus via apt and I get the following error when trying to run it

```bash
$ mate-optimus-applet 
Traceback (most recent call last):
  File "/usr/bin/mate-optimus-applet", line 20, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available
```

But I can't find any listing for AppIndicator3 on pip.

Any advice would be appreciated.

**Comment by N0rbert** [comment]
Please report this to Launchpad by `apport-bug mate-optimus` 
with all relevant information including information about your Python environment and modules. You should mention all the details about the Python3, do you have Anaconda or something similar.
